// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/labstack/echo/v4"
	"golang-test/configs"
	"golang-test/handlers"
	"golang-test/repositories"
	"golang-test/routes"
	"golang-test/services"
)

// Injectors from wire.go:

func InitializeRouter() *echo.Echo {
	config := configs.NewEnv()
	db := configs.NewDB(config)
	productRepository := repositories.NewProductRepository(db)
	client := configs.NewRedis(config)
	redisRepository := repositories.NewRedisRepository(client)
	productService := services.NewProductService(productRepository, redisRepository)
	productHandler := handlers.NewProductHandler(productService)
	echoEcho := routes.NewRouter(productHandler)
	return echoEcho
}
